---
/preservation/config:
  get:
    x-mojo-to: Preservation#config
    operationId: getPreservationconfig
    description: This resource returns a list of options needed for the Preservation Vue app. EXPERIMENTAL - DO NOT RELY on this, it is subject to change!
    summary: get the Preservation config
    tags:
      - preservation
    produces:
      - application/json
    responses:
      200:
        description: The Preservation module config
        schema:
          $ref: "../swagger.yaml#/definitions/preservation_config"
      400:
        description: Bad request
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      403:
        description: Access forbidden
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      500:
        description: |
          Internal server error. Possible `error_code` attribute values:

          * `internal_server_error`
        schema:
          $ref: "../swagger.yaml#/definitions/error"
      503:
        description: Under maintenance
        schema:
          $ref: "../swagger.yaml#/definitions/error"
    x-koha-authorization:
      permissions:
        preservation: 1
