---
type: object
properties:
  settings:
    type: object
    description: List of sysprefs used for the Preservation module
  permissions:
    type: object
    description: List of permissions of the logged in user used for the Preservation module
additionalProperties: false
